### ISSUE TITLE
Why are there some differences between the figures of the paper and repo?

### ISSUE THREAD

**Issue by zhimin-z** [MikeGu721/XiezhiBenchmark#8]
The figure in the paper:
![image](https://github.com/MikeGu721/XiezhiBenchmark/assets/8592144/d14a174d-ef92-4b58-983f-c2f9bba88423)
The figure in the repo:
![image](https://github.com/MikeGu721/XiezhiBenchmark/assets/8592144/17c04a00-7c48-45b4-9ef2-ae4fc18748b2)

@zxx000728 @MikeGu721 @yixin-zhu

**Comment by MikeGu721** [comment]
Because paper includes both new evaluation method & new dataset, so we test this new evaluation method on other existing dataset. But in github, we have no right to place the json file of other work here, so we only put the performance of new evaluation method on our dataset here.
